# Generated by Django 4.1.7 on 2023-03-14 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CategoryName", models.CharField(max_length=100, unique=True)),
                ("CategoryDescription", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ProductName", models.CharField(max_length=150)),
                ("ProductDescription", models.CharField(max_length=500)),
                (
                    "ProductImage",
                    models.ImageField(
                        blank=True, null=True, upload_to="Products/Images/"
                    ),
                ),
                ("ProductQuantity", models.IntegerField()),
                ("ProductPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ProductCreated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ProductCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                    ),
                ),
            ],
        ),
    ]
